config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'how_it_works' => 'products#how_it_works', as: 'how_it_works'
  # devise_for :sellers
  devise_for :sellers, :controllers => { registrations: 'registrations' }

  devise_scope :seller do

    get '/profile' => 'registrations#profile', :as => 'profile_registration'
  end


  # You can have the root of your site routed with "root"
  root 'products#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :seller
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment :photo,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  validates :photo, attachment_presence: true
  validates_with AttachmentPresenceValidator, attributes: :photo
  validates_with AttachmentSizeValidator, attributes: :photo, less_than: 1.megabytes

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    format("%.2f", price_in_dollars)
  end
end

app/models/seller.rb
class Seller < ActiveRecord::Base

  has_many :products, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def how_it_works
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price_in_cents, :seller_id, :photo)

    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  def profile
   if !seller_signed_in?
     redirect_to new_seller_registration_path
   end
  end

  private
    def sign_up_params
      params.require(:seller).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:seller).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Offerup</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">


    <nav class="navbar navbar-light bg-faded">
      <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
        &#9776;
      </button>
      <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
        <a class="navbar-brand" href="<%= root_path %>">OfferUPP</a>
        <ul class="nav navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="<%= how_it_works_path %>">How it Works</a>
          </li>
        </ul>

        <ul class="nav navbar-nav pull-xs-right">

          <% if seller_signed_in? %>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><%= current_seller.first_name %></a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="<%= profile_registration_path %>">Profile</a>
              <%= link_to('Logout', destroy_seller_session_path, :method => :delete, class: "dropdown-item") %>
            </div>
          </li>

          <% else %>
          <li class="nav-item">
            <%= link_to('Login', new_seller_session_path, class: "btn btn-success")  %>
          </li>
          <li class="nav-item">
            <%= link_to('Sign Up & Start Selling', new_seller_registration_path, class: "btn btn-primary")  %>
          </li>
          <% end %>

        </ul>


      </nav>
    </div>
    <%= yield %>

  </body>
  </html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <%= f.hidden_field :seller_id, value: current_seller.id %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br>
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="field">
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/how_it_works.html.erb
<div class="container" id="how_it_works">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>How It Works</h1>
      <article>
        What was going through the minds of all of Chuck Norris' victims before they died? His shoe, Chuck Norris' hand is the only hand that can beat a Royal Flush Chuck Norris was once stuck in a rut, that rut is now known as the Grand Canyon, Chuck Norris doesn't wash his clothes, he disembowels them. Chuck Norris is the only man to ever defeat a brick wall in a game of tennis, Chuck Norris doesn't wear a watch. HE decides what time it is, What was going through the minds of all of Chuck Norris' victims before they died? His shoe. Try to imagine from where Chuck Norris gets his amazing powers. He gets it from his loveley cat, which named CHUCK THE SECOND, When Chuck Norris does a pushup, he isn't lifting himself up, he's pushing the Earth down Chuck Norris can slam a revolving door Chuck Norris is the only man to ever defeat a brick wall in a game of tennis.

Chuck Norris uses pepper spray to spice up his steaks. Contrary to popular belief, America is not a democracy, it is a Chucktatorship. When Chuck Norris does a pushup, he isn't lifting himself up, he's pushing the Earth down, Chuck Norris doesn't wear a watch. HE decides what time it is, Chuck Norris once roundhouse kicked someone so hard that his foot broke the speed of light, went back in time, and killed Amelia Earhart while she was flying over the Pacific Ocean, There is no chin behind Chuck Norris' beard. There is only another fist Chuck Norris doesn't wear a watch. HE decides what time it is, If you ask Chuck Norris what time it is, he always says, "Two seconds 'til." After you ask, "Two seconds 'til what?" he roundhouse kicks you in the face Chuck Norris went to a Raiders game using a Lakers ticket... and got a sideline pass, A Handicapped parking sign does not signify that this spot is for handicapped people. It is actually in fact a warning, that the spot belongs to Chuck Norris and that you will be handicapped if you park there.

Chuck Norris does NOT plank. He merely pushes the Earth lower Chuck Norris doesn't wash his clothes, he disembowels them. Chuck Norris can lead a horse to water AND make it drink, Chuck Norris once roundhouse kicked someone so hard that his foot broke the speed of light, went back in time, and killed Amelia Earhart while she was flying over the Pacific Ocean. Chuck Norris wore sunglasses to protect the sun from his intense gaze, Chuck Norris is the only man to ever defeat a brick wall in a game of tennis, When Chuck Norris does a pushup, he isn't lifting himself up, he's pushing the Earth down. Remember the Soviet Union? They decided to quit after watching a DeltaForce marathon on Satellite TV The quickest way to a man's heart is with Chuck Norris' fist. Chuck Norris is the only man to ever defeat a brick wall in a game of tennis.

Chuck Norris is ten feet tall, weighs two-tons, breathes fire, and could eat a hammer and take a shotgun blast standing, Someone once videotaped Chuck Norris getting pissed off. It was called Walker: Texas Chain Saw Massacre Chuck Norris is so fast, he can run around the world and punch himself in the back of the head, How many roundhouse kicks does it take to get to the center of a tootsie pop? Just one. From Chuck Norris.

      </article>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="hero">
  <div class="container-fluid">
    <div class="row">
      <div class="hero-heading">
      <h2>
      Offers from Your Community<br />
        Find it on OfferUPP.</h2>
        <p>
          Browse. Buy. Done.
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-3 col-md-6">
        <form>
          <div class="input-group input-group-lg">
            <input type="text" class="form-control" placeholder="What are you looking for..." />
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Find Services</button>
            </span>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>



<div class="container-fluid">

<h1>Offers Currently for Sale!</h1>


<% @products.each_slice(4) do |product| %>
<div class="row">
  <% product.each do |product| %>
  <div class="col-md-3">
    <div class="card">
      <%= image_tag(product.photo.url(:medium), class: "card-img-top") %>

      <div class="card-block">
        <h4 class="card-title"><%= product.name %></h4>
        <p class="card-text"><%= product.description %></p>
        <%= link_to 'View', product,  class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

<% end %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>
<% if seller_signed_in? %>
  <%= render 'form' %>
<% else %>
  <h3>Sign up to start selling today!</h3>
  <%= link_to('Login', new_seller_session_path, class: "btn btn-primary")  %>
  <%= link_to('Sign Up & Start Selling', new_seller_registration_path, class: "btn btn-primary")  %>
<% end %>

<%= link_to 'Back', root_path %>

app/views/products/show.html.erb
<div class="container">


<p id="notice"><%= notice %></p>

<%= image_tag(@product.photo.url(:medium), class: "img-fluid") %>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  $<%= @product.formatted_price %>
</p>


<%= link_to 'Back', root_path, class: 'btn btn-danger' %>
</div>

app/views/sellers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>